// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: disconf_grpc_service.proto

package com.baidu.disconf.core.grpc.auto;

public final class DisconfGrpcService {
  private DisconfGrpcService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032disconf_grpc_service.proto\032\031google/pro" +
      "tobuf/any.proto\032\037google/protobuf/timesta" +
      "mp.proto\";\n\007Message\022\014\n\004type\030\001 \001(\t\022\"\n\004bod" +
      "y\030\003 \001(\0132\024.google.protobuf.Any2*\n\007Request" +
      "\022\037\n\007request\022\010.Message\032\010.Message\"\00028\n\rReq" +
      "uestStream\022\'\n\rrequestStream\022\010.Message\032\010." +
      "Message\"\0000\0012>\n\017BiRequestStream\022+\n\017biRequ" +
      "estStream\022\010.Message\032\010.Message\"\000(\0010\001B$\n c" +
      "om.baidu.disconf.core.grpc.autoP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "Type", "Body", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
