// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: disconf_grpc_service.proto

package com.baidu.disconf.core.grpc.auto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>.google.protobuf.Any body = 3;</code>
   */
  boolean hasBody();
  /**
   * <code>.google.protobuf.Any body = 3;</code>
   */
  com.google.protobuf.Any getBody();
  /**
   * <code>.google.protobuf.Any body = 3;</code>
   */
  com.google.protobuf.AnyOrBuilder getBodyOrBuilder();
}
